#!/bin/bash

source check_program/bash_tests

GIT_NAME=$1
REPO_NAME=0
RECURSIVE=0
VG_CHECK=0

function warnings()
{
    echo -e "\e[33m [ WARNINGS CHECK... ] \e[37m"
    sleep 1.2
    echo -e "\e[36m [ WARNINGS LOGS ] \e[37m" > ../tests.log
    make re >> ../tests.log
    make re
    if [ ${?} != '0' ]; then
        sleep 0.5
        echo -e "\e[31m [ WARNINGS ERROR / TRY AGAIN.. ]"
        ls
        exit
    else
        clear
        echo -e "\e[32m [ WARNINGS ✔️  / GOOD JOB BIG BOY.. ]"
    fi
}

function norms()
{
    echo -e "\e[33m [ NORMS CHECK... ] \e[37m"
    make fclean &>/dev/null
    sleep 1
    norminette -T4 -i4 -A -v | sed -n '/rule/,$p'
    echo -e "\n\e[36m [ NORMS LOGS ] \e[37m" >> ../tests.log
    norminette -T4 -i4 -A -v | sed -n '/rule/,$p' >> ../tests.log
    while [ $RECURSIVE != 1 ]
    do
        read -p "Do you think you don't have any coding style error ? [Y/N] " -r check_norms
        if [[ $check_norms =~ ^[Yy]$  ]]; then
            clear
            echo -e "\e[32m [ WARNINGS ✔️  / GOOD JOB BIG BOY.. ]"
            echo -e "\e[32m [ NORMS ✔️  / NICE ONE.. ]"
            RECURSIVE=1
        elif [[ $check_norms =~ ^[Nn]$ ]]; then
            echo -e "\e[31m [ NORMS ERROR / TRY AGAIN.. ]"
            exit
        else
            echo -e "\e[34m [ WRONG ANSWER ] \e[37m"
        fi
    done
}

function valgriind()
{
    echo -e "\e[33m [ VALGRIND ERROR CHECK... ] \e[37m"
    make re &>/dev/null
    read -p "Do command :  " -r vg_command
    $vg_command &>/dev/null
    if [ ${?} = '127' ] || [ $? = '126' ]; then
        echo -e "\e[31m [ MAUVAISE COMMANDE ! ]"
        exit 1
    fi
    script -c "valgrind $vg_command" output.log &>/dev/null
    echo -e "\n\e[36m [ VALGRIND LOGS ] \e[37m" >> ../tests.log
    cat output.log | sed -n '/Memcheck/,/contexts/p' >> ../tests.log
    gcc ../check_program/check_valgrind.c ../check_program/my_str_to_word_tab.c
    ./a.out output.log
    if [ ${?} = '0' ]; then
        echo -n " [==      ] 25%"
        sleep 0.65
        echo -e "\r [====    ] 50%"
        sleep 0.65
        clear
        echo -e "\e[32m [ WARNINGS ✔️  / GOOD JOB BIG BOY.. ]"
        echo -e "\e[32m [ NORMS ✔️  / NICE ONE.. ] \e[37m"
        echo -e "\e[32m [ VALGRIND ERROR ✔️  /\e[33m VALGRIND FREE CHECK... ] \e[37m"
        sleep 1
        gcc ../check_program/check_free.c ../check_program/my_str_to_word_tab.c
        ./a.out output.log
        if [ ${?} = '0' ]; then
            rm a.out && rm output.log
            echo -n " [======  ] 75%"
            sleep 0.8
            echo -e "\r [========] 100%"
            sleep 0.8
            clear
            echo -e "\e[32m [ WARNINGS ✔️  / GOOD JOB BIG BOY.. ]"
            echo -e "\e[32m [ NORMS ✔️  / NICE ONE.. ]"
            echo -e "\e[32m [ VALGRIND ERROR ✔️  / VALGRIND FREE ✔️  ]"
            VG_CHECK=1
        else
            echo -n " [======  ] 75%"
            sleep 0.8
            echo -e "\r [========] 100%"
            sleep 0.8
            clear
            echo -e "\e[32m [ WARNINGS ✔️  / GOOD JOB BIG BOY.. ]"
            echo -e "\e[32m [ NORMS ✔️  / NICE ONE.. ]"
            echo -e "\e[32m [ VALGRIND ERROR ✔️  /\e[33m NOT ENOUGH FREE ! ]"
        fi
    else
        echo -e "\e[31m [ TOO MANY VALGRIND ERROR / TRY AGAIN.. ]"
        exit
    fi
}

function criterion()
{
    echo -e "\e[33m [ TESTS CRITERION CHECK... ] \e[37m"
    sleep 1.7
    cd tests &>/dev/null
    if [ ${?} = '0' ]; then
        cd ..
        echo -e "\n\e[36m [ CRITERION LOGS ] \e[37m" >> ../tests.log
        script -c "make tests_run" cr_log &>/dev/null
        cat cr_log | sed -n '/make/,/Synthèse/p' >> ../tests.log
        make tests_run
        if [ ${?} = '0' ]; then
            sleep 1.5
            rm cr_log
            if [ $VG_CHECK == 1 ]; then
                clear
                echo -e "\e[32m [ WARNINGS ✔️  / GOOD JOB BIG BOY.. ]"
                echo -e "\e[32m [ NORMS ✔️  / NICE ONE.. ]"
                echo -e "\e[32m [ VALGRIND ERROR ✔️  / VALGRIND FREE ✔️  ]"
                echo -e "\e[32m [ TESTS CRITERION ✔️  / A REAL BOSS.. ]"
            else
                echo -e "\e[32m [ WARNINGS ✔️  / GOOD JOB BIG BOY.. ]"
                echo -e "\e[32m [ NORMS ✔️  / NICE ONE.. ] \e[37m"
                echo -e "\e[32m [ VALGRIND ERROR ✔️  /\e[33m NOT ENOUGH FREE ! ]"
                echo -e "\e[32m [ TESTS CRITERION ✔️  / A REAL BOSS.. ]"
            fi
        else
            echo -e "\e[31m [ TESTS CRITERION ERROR / TRY AGAIN.. ]"
            exit
        fi
    else
        if [ $VG_CHECK == 1 ]; then
            clear
            echo -e "\e[32m [ WARNINGS ✔️  / GOOD JOB BIG BOY.. ]"
            echo -e "\e[32m [ NORMS ✔️  / NICE ONE.. ]"
            echo -e "\e[32m [ VALGRIND ERROR ✔️  / VALGRIND FREE ✔️  ]"
            echo -e "\e[35m [ NO TESTS CRITERION :( ]"
        else
            clear
            echo -e "\e[32m [ WARNINGS ✔️  / GOOD JOB BIG BOY.. ]"
            echo -e "\e[32m [ NORMS ✔️  / NICE ONE.. ] \e[37m"
            echo -e "\e[32m [ VALGRIND ERROR ✔️  /\e[33m NOT ENOUGH FREE ! ]"
            echo -e "\e[35m [ NO TESTS CRITERION :( ]"
        fi
    fi
}

function tests()
{
    echo -e -n "\n\e[33m [ $REPO_R_NAME TESTS CHECK... ] \e[37m\n"
    sleep 1.4
    bash_tests
    if [ ${?} = '0' ]; then
        echo -e "\r\n\e[32m [ $REPO_R_NAME TESTS ✔️  ] \e[37m"
        echo -e "\e[32m\e[5m\e[1m      [ CLEAN WORK ]\e[25m"
        make fclean &>/dev/null
        exit 0
    else
        echo -e "\r\n\e[31m [ $REPO_R_NAME TESTS ERROR ] \e[37m"
        echo -e "\e[31m\e[5m\e[1m      [ TESTS FAILED ]\e[25m"
        make fclean &>/dev/null
        exit 1
    fi
}

function usage()
{
    echo "*CONTINIOUS INTEGRATION FAILED*"
    echo "syntax error.."
    echo $1
    echo "USAGE"
    echo "    ./incontinue {REPO_NAME} {REPO_USERNAME}"
    exit 1
}

if [[ -z "$1" ]]; then
    usage "incontinue: not enough arguments"
elif [[ "$2" ]]; then
    usage "incontinue: too many arguments"
fi
REPO_NAME="${GIT_NAME#*/}"
REPO_R_NAME=$(echo $REPO_NAME | rev | cut -c 5- | rev)
if [ -d  "$REPO_R_NAME" ]; then
    rm -rf $REPO_R_NAME &>/dev/null
fi
echo -e "\e[33m [ CLONAGE DU PROJET TECH... ] \e[37m"
git clone $GIT_NAME 
if [ ${?} != '0' ]; then
    usage "incontinue: invalid repository or connection lost"
fi
echo $REPO_R_NAME
cd $REPO_R_NAME
warnings
norms
valgriind
criterion
tests
